name: Build a11

on:
  workflow_dispatch:

jobs:
  build-and-modify-flutter:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.24.0'

    - name: Find flutter.groovy file
      id: find-flutter-groovy
      run: |
        # 查找flutter.groovy文件
        flutter_groovy_path=$(find $FLUTTER_ROOT -name flutter.groovy)
        echo "Found flutter.groovy at path: $flutter_groovy_path"
        echo "::set-output name=path::$flutter_groovy_path"

    - name: Print flutter.groovy content
      run: |
        # 打印flutter.groovy文件的完整代码
        cat ${{ steps.find-flutter-groovy.outputs.path }}

    - name: Remove ShrinkResources related if block
      run: |
        # 删除与ShrinkResources相关的if代码块
        if [ -f "${{ steps.find-flutter-groovy.outputs.path }}" ]; then
          sed -i '/ShrinkResources/d' ${{ steps.find-flutter-groovy.outputs.path }}
        else
          echo "flutter.groovy file not found."
          exit 1
        fi

    # ... 其他构建步骤 ...



    - name: Build APK
      run: |
        flutter clean
        flutter build apk --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=tiny_computer/sdi

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: tiny-computer-apk
        path: build/app/outputs/flutter-apk/app-arm64-release.apk
