name: Build tiny_computer

on:
  workflow_dispatch:

jobs:
  build-tiny-computer:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout tiny_computer repository
      uses: actions/checkout@v2
      with:
        repository: 'Cateners/tiny_computer'
        submodules: 'recursive'  # 确保子模块也被检出

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        check-latest: false
        server-id: github
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN
        overwrite-settings: true

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: '3.24.0'

    - name: Install dependencies
      run: |
        flutter pub get
        # 确保所有依赖项都已安装，包括子模块

    - name: Prepare build environment
      run: |
        wget --tries=3 https://github.com/Cateners/tiny_computer/releases/download/v1.0.18/debian-xfce.tar.xz || (echo "Failed to download debian-xfce.tar.xz" && exit 1)
        mkdir -p assets
        split -b 98M debian-xfce.tar.xz assets/debian.tar.xz.

    - name: Build APK
      run: |
        flutter clean
        flutter build apk --target-platform android-arm64 --split-per-abi --obfuscate --split-debug-info=tiny_computer/sdi

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: tiny-computer-apk
        path: build/app/outputs/flutter-apk/app-arm64-release.apk
